### ISSUE TITLE
Cannot read properties of undefined (reading 'uses')

### ISSUE THREAD

**Issue by LwkasCrystian** [e-enes/invitron#15]
The bot is perfect, but after a few hours it starts giving the following error:

```
Uncaught Exception
Message: Cannot read properties of undefined (reading 'uses')

Name: TypeError
Cause: undefined
Source: undefined

Stack:
TypeError: Cannot read properties of undefined (reading 'uses')
    at file:///root/invite-tracker/dist/events/guild/member/GuildMemberAdd.js:1:832
    at _Collection.find (/root/invite-tracker/node_modules/.pnpm/@discordjs+collection@1.5.3/node_modules/@discordjs/collection/dist/index.js:172:11)
    at w.execute (file:///root/invite-tracker/dist/events/guild/member/GuildMemberAdd.js:1:807)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

How can I solve?

**Comment by louiszn** [comment]
thanks for reporting the issue

**Comment by louiszn** [comment]
#19
